
POST http://localhost:3000/players
Content-Type: application/json
Accept: application/json

{
  "username": "SarcasticoMartinez2"
}

###
GET http://localhost:3000/players/
Accept: application/json

###
PUT http://localhost:3000/players/
Content-Type: application/json
Accept: application/json

{
  "username": "testUpdatedToo"
}

###

POST http://localhost:3000/games/63bead9885c186047925301a
Content-Type: application/json
Accept: application/json

###

GET http://localhost:3000/games/63bead9885c186047925301a
Content-Type: application/json
Accept: application/json

###

GET http://localhost:3000/ranking
Content-Type: application/json
Accept: application/json

###

GET http://localhost:3000/ranking/loser
Content-Type: application/json
Accept: application/json

###

GET http://localhost:3000/ranking/winner
Content-Type: application/json
Accept: application/json

###
POST http://localhost:3000/login
