
POST http://localhost:3000/players/create
Content-Type: application/json
Accept: application/json

{
  "username": "perrete",
  "password": "testPassword"
}

###
GET http://localhost:3000/players
Content-Type: application/json
Accept: application/json

###
PUT http://localhost:3000/players/update/4
Content-Type: application/json
Accept: application/json

{
  "username": "testUpdatedToo",
  "password": "testPassword"
}

###
