POST http://localhost:3000/players/create
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "testPassword"
}

###
GET http://localhost:3000/players
Content-Type: application/json
Accept: application/json

###
